pipeline:
  agent: any

  environment:
    REACT_APP: "example-react-master"
    DEPLOY_DIR: "/var/www/html/example-react-master"
    NGINX_CONF: "/etc/nginx/sites-available/example-react-master.conf"

  stages:
    - stage: Prepare
      steps:
        - script: |
            echo "Copying local React app into Jenkins workspace..."
            cp -r /var/www/example-react-master/client/* .

    - stage: Build
      steps:
        - script: |
            echo "Installing dependencies..."
            npm install
            echo "Building the React app..."
            npm run build
      post:
        failure:
          - script: |
              echo "Build failed! Please check the logs for errors."

    - stage: Test
      when:
        expression: BUILD_STATUS == "SUCCESS"
      steps:
        - script: |
            echo "Running tests..."
            npm test

    - stage: Deploy
      when:
        expression: BUILD_STATUS == "SUCCESS"
      steps:
        - script: |
            echo "Deploying the app to Nginx server..."
            sudo cp -r /var/www/example-react-master/client/build/* $DEPLOY_DIR
            echo "Reloading Nginx..."
            sudo systemctl reload nginx

  post:
    always:
      - script: |
          echo "Pipeline finished!"

    success:
      - script: |
          echo "Successfully built, tested, and deployed!"

    failure:
      - script: |
          echo "Build, test, or deploy failed!"



